/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package webtermometro.visao;

import webtermometro.Serialazer;
import webtermometro.entidades.Parametrizacao;

/**
 *
 * @author guilhermeluizcamposodossantossilva
 */
public class ParametrizacaoFrame extends javax.swing.JFrame {

    private Parametrizacao parametrizacao;
    private TelaPrincipalFrame tela;

    /**
     * Creates new form ParametrizacaoFrame
     */
    public ParametrizacaoFrame() {
        initComponents();
    }

    /**
     * Creates new form ParametrizacaoFrame
     */
    public ParametrizacaoFrame(TelaPrincipalFrame tela) {
        initComponents();
        this.tela = tela;
        this.parametrizacao = tela.getParametrizacao();
       
        if (this.parametrizacao != null) {
            preencherCampos();
        } else {
            this.parametrizacao = new Parametrizacao();
        }

    }

    private void preencherCampos() {

        txtPesoTempo.setText(parametrizacao.getPesoTempo().toString());
        txtPesoAcesso.setText(parametrizacao.getPesoAcesso().toString());
        txtAcessoIdeal.setText(parametrizacao.getNumAcessoMedioDiaIdeal().toString());
        txtTempoIdeal.setText(parametrizacao.getTmpGastoMedioSecIdeal().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTempoIdeal = new javax.swing.JTextField();
        txtAcessoIdeal = new javax.swing.JTextField();
        txtPesoTempo = new javax.swing.JTextField();
        txtPesoAcesso = new javax.swing.JTextField();

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        jLabel1.setText("Tempo ideal de navegação em segundos ");

        jLabel2.setText("Número de acessos ideal por dia");

        jLabel3.setText("Peso do tempo de navegação");

        jLabel4.setText("Peso do número de acesso");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(34, 34, 34)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2)
                            .add(jLabel3)
                            .add(jLabel4))
                        .add(43, 43, 43)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(txtPesoAcesso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txtPesoTempo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txtAcessoIdeal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txtTempoIdeal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(144, 144, 144)
                        .add(btnSalvar)
                        .add(18, 18, 18)
                        .add(btnCancelar)))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {btnCancelar, btnSalvar}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.linkSize(new java.awt.Component[] {txtAcessoIdeal, txtPesoAcesso, txtPesoTempo, txtTempoIdeal}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(13, 13, 13)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(txtTempoIdeal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(txtAcessoIdeal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(27, 27, 27)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(txtPesoTempo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(txtPesoAcesso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(28, 28, 28)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnSalvar)
                    .add(btnCancelar))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {btnCancelar, btnSalvar}, org.jdesktop.layout.GroupLayout.VERTICAL);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        parametrizacao.setNumAcessoMedioDiaIdeal(Double.valueOf(txtAcessoIdeal.getText()));
        parametrizacao.setTmpGastoMedioSecIdeal(Double.valueOf(txtTempoIdeal.getText()));
        parametrizacao.setPesoAcesso(Integer.valueOf(txtPesoAcesso.getText()));
        parametrizacao.setPesoTempo(Integer.valueOf(txtPesoTempo.getText()));

        
        Serialazer.serializar("parametrizacao.data", parametrizacao);
        
        tela.setParametrizacao(parametrizacao);
        
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParametrizacaoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParametrizacaoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParametrizacaoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParametrizacaoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParametrizacaoFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtAcessoIdeal;
    private javax.swing.JTextField txtPesoAcesso;
    private javax.swing.JTextField txtPesoTempo;
    private javax.swing.JTextField txtTempoIdeal;
    // End of variables declaration//GEN-END:variables
}
