/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package webtermometro.visao;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import webtermometro.Core;
import static webtermometro.Serialazer.deserializar;
import static webtermometro.Serialazer.serializar;
import webtermometro.entidades.Parametrizacao;
import webtermometro.entidades.Resultado;

/**
 *
 * @author guilhermeluizcamposodossantossilva
 */
public class TelaPrincipalFrame extends javax.swing.JFrame {

    Parametrizacao parametrizacao;

    /**
     * Creates new form TelaPrincipalFrame
     */
    public TelaPrincipalFrame() {

        initComponents();

        parametrizacao = (Parametrizacao) deserializar("parametrizacao.data");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCarregarLog = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuConfigurar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Arquivo");

        menuCarregarLog.setText("Novo");
        menuCarregarLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCarregarLogActionPerformed(evt);
            }
        });
        jMenu1.add(menuCarregarLog);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Parametrização");

        menuConfigurar.setText("Configurar");
        menuConfigurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConfigurarActionPerformed(evt);
            }
        });
        jMenu2.add(menuConfigurar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 562, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 412, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCarregarLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCarregarLogActionPerformed

        JFileChooser fileChooser ;
        Object caminho;
        
        caminho = deserializar("caminhoarquivo.data");

        if (caminho != null) {
            fileChooser = new JFileChooser((String) caminho);
        } else {
            fileChooser = new JFileChooser();
        }

        int returnVal = fileChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();

            if (parametrizacao != null) {

                serializar("caminhoarquivo.data", file.getPath());

                Resultado resultado = Core.processar(file.getPath(), parametrizacao);

                JOptionPane.showMessageDialog(this, "Sua nota foi " + resultado.getNotaGeral());

            } else {
                JOptionPane.showMessageDialog(this, "Parametrize antes de escolher um log");
            }

        }

    }//GEN-LAST:event_menuCarregarLogActionPerformed

    private void menuConfigurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConfigurarActionPerformed

        new ParametrizacaoFrame(this).setVisible(true);

    }//GEN-LAST:event_menuConfigurarActionPerformed

    public Parametrizacao getParametrizacao() {
        return parametrizacao;
    }

    public void setParametrizacao(Parametrizacao parametrizacao) {
        this.parametrizacao = parametrizacao;
    }

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuCarregarLog;
    private javax.swing.JMenuItem menuConfigurar;
    // End of variables declaration//GEN-END:variables
}
